/**
 * Emergency Alerts
 * This application notifies users about an emergency within a geographical area, you can also obtain users information and its location within an area to plan possible evacuations or other uses
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.resource;


import org.openapitools.server.model.*;
import org.openapitools.server.response.*;

import java.util.*;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;


import org.openapitools.server.model.User;



import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;
import android.content.Context;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;
import android.util.Log;
import android.widget.Toast;


public class LocationResource {

    private Context context;
    private RequestQueue request;

    private LocationResponse locationResponse;

    public LocationResource(Context context) {
        this.context = context;
        request = Volley.newRequestQueue(context);

    }

  public void executeMethod(LocationResponse response){

        locationResponse=response;

      switch (response.getMethod()){
          case "getUsers":
            getUsers(response.getParams().getlatitude(),response.getParams().getlongitude(),response.getParams().getradius());
            break;
      }


  }

  /**
  * Gets users within an area
  * Obtain information and location of users within a geographical area
   * @param latitude 
   * @param longitude 
   * @param radius 
   * @return User
  */
  public User getUsers (Double latitude, Double longitude, Double radius){

    //TODO: Process the information, generate a reply, etc.

      //TODO: Put your object to return
      return null;
  }


}
