/**
 * Emergency Alerts
 * This application notifies users about an emergency within a geographical area, you can also obtain users information and its location within an area to plan possible evacuations or other uses
 *
 * OpenAPI spec version: 1.0
 * Contact: info@spilab.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.model;

import org.openapitools.server.model.User;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;



@ApiModel(description = "")
public class EmergencyResponse {
  
  @SerializedName("emergencyId")
  private Long emergencyId = null;
  @SerializedName("user_information")
  private User userInformation = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Long getEmergencyId() {
    return emergencyId;
  }
  public void setEmergencyId(Long emergencyId) {
    this.emergencyId = emergencyId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public User getUserInformation() {
    return userInformation;
  }
  public void setUserInformation(User userInformation) {
    this.userInformation = userInformation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmergencyResponse emergencyResponse = (EmergencyResponse) o;
    return (this.emergencyId == null ? emergencyResponse.emergencyId == null : this.emergencyId.equals(emergencyResponse.emergencyId)) &&
        (this.userInformation == null ? emergencyResponse.userInformation == null : this.userInformation.equals(emergencyResponse.userInformation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.emergencyId == null ? 0: this.emergencyId.hashCode());
    result = 31 * result + (this.userInformation == null ? 0: this.userInformation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmergencyResponse {\n");
    
    sb.append("  emergencyId: ").append(emergencyId).append("\n");
    sb.append("  userInformation: ").append(userInformation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
